name: "day8 prod build-deploy-ecs"

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  IMAGE_NAME: "bootcamp-prod-2-tier-flask"
  ECR_REGISTRY: "366140438193.dkr.ecr.ap-south-1.amazonaws.com"
  ECR_REPOSITORY: "bootcamp-prod-2-tier-flask"
  ACCOUNT_ID: "366140438193"
  ECS_CLUSTER: "prod-2-tier-flask-cluster"
  ECS_REGION: "ap-south-1"
  ECS_SERVICE: "prod-2-tier-flask-service"
  ECS_TASK_DEFINITION: "prod-2-tier-flask"
  ECS_APP_CONTAINER_NAME: "2-tier-flask"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      #   configure aws credentials
      - name: Configure AWS Credentials
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.ECS_REGION  }} 

      - name: Login to Amazon ECR
        if: ${{ github.ref == 'refs/heads/main' }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
          registries: ${{ env.ACCOUNT_ID }}

      - name: Push image to Amazon ECR
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd day8/day6/src
          docker build -t  ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG  }}  . 
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

  deploy:
    needs: [build]
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      #   configure aws credentials
      - name: Configure AWS Credentials
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.ECS_REGION  }} 
    
      - name: Download task definition for web
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} \
          --query taskDefinition > task-definition.json
          ls -l task-definition.json

      - name: Fill in the new image ID for web in the Amazon ECS task definition
        if: ${{ github.ref == 'refs/heads/main' }}
        id: task-def-web
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          # task-definition: ${{ env.ECS_TASK_DEFINITION }}
          task-definition: task-definition.json
          container-name: ${{ env.ECS_APP_CONTAINER_NAME }}
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Deploy app on Amazon ECS task definition
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def-web.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          # wait-for-service-stability: true
      