# 366140438193.dkr.ecr.ap-south-1.amazonaws.com/bootcampflask:v1
name: day8 build

on: 
  workflow_dispatch:
env:
  ECR_REPO: 366140438193.dkr.ecr.ap-south-1.amazonaws.com/bootcamp-prod-2-tier-flask

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Replace with your AWS region

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{  env.ECR_REPO }}
    - name: Build, Tag, and Push Docker Image
      run: |
        cd day8/day6/src
        docker build -t ${{  env.ECR_REPO }}:day8 .
        docker push ${{  env.ECR_REPO }}:day8
